"""
Static glossary for the Nokia RAML (raml21.xsd) file-format elements and
attributes themselves -- as opposed to RAN configuration parameters, which
live in data/parameters.json. This covers the handful of fixed XML
constructs every commissioning/configuration file is built from.
"""

ELEMENTS: dict[str, dict] = {
    "raml": {
        "description": (
            "The root element of a Nokia RAML (Radio Access Markup Language) file, the XML "
            "format used by Nokia BTS Site Manager / NetAct to export and import RAN "
            "configuration data ('CM data') for AirScale and Flexi Zone base stations. "
            "The `version` attribute (e.g. \"2.1\") identifies the RAML schema revision, and "
            "the `xmlns` value points at the schema name (raml21.xsd) rather than a real URL."
        ),
        "category": "File Format",
        "confidence": "high",
    },
    "cmData": {
        "description": (
            "Holds one Configuration Management (CM) data set: the complete list of managed "
            "objects being created, updated, or deleted. The `type` attribute is usually "
            "\"plan\" (a configuration plan/snapshot), `scope` is usually \"all\" (a full "
            "data set rather than a delta), and `id` is an internal numeric identifier for "
            "this data set generated by the exporting tool."
        ),
        "category": "File Format",
        "confidence": "high",
    },
    "header": {
        "description": (
            "Metadata block describing the provenance of this CM data file -- who/what "
            "produced or last modified it, and when. Contains one or more `log` entries."
        ),
        "category": "File Format",
        "confidence": "high",
    },
    "log": {
        "description": (
            "One audit-trail entry recording a single create/modify export event: `action` "
            "(e.g. create, created, modified), `dateTime` (UTC timestamp), `user` (the "
            "operator or service account), `appInfo` (the tool that produced it, e.g. "
            "\"Nokia BTS Site Manager\" or \"Flexi TRS Manager\"), and `appVersion` (that "
            "tool's version/build string)."
        ),
        "category": "File Format",
        "confidence": "high",
    },
    "managedObject": {
        "description": (
            "Represents one instance of a Nokia Managed Object Class (MOC) -- a piece of "
            "hardware (e.g. a radio module), a logical radio cell, a transport endpoint, or "
            "a feature/function configuration group. Identified by its `distName` "
            "(Distinguished Name), a slash-separated path of parent/child object instances "
            "such as `MRBTS-1/EQM-1/APEQM-1/RMOD-1` that shows exactly where this object "
            "sits in the site's hierarchy. The `class` attribute gives the fully-qualified "
            "MOC name (a Nokia-internal namespace like `com.nokia.srbts.eqm:RMOD` or "
            "`NOKLTE:LNCEL`); the part after the colon is the short class name used "
            "throughout this tool. `operation` says what this file does to the object "
            "(create/update/delete), and `version` pins the software/model-file build the "
            "object's parameter set is defined against."
        ),
        "category": "File Format",
        "confidence": "high",
    },
    "p": {
        "description": (
            "A single scalar configuration parameter: `name` is the parameter's identifier "
            "in Nokia's parameter dictionary, and the element's text content is its value "
            "(a number, enum string, boolean, or free text). An empty `<p name=\"x\"/>` "
            "means the parameter is present but has no value set (often left to its default)."
        ),
        "category": "File Format",
        "confidence": "high",
    },
    "list": {
        "description": (
            "A repeating/table-like configuration parameter -- e.g. a set of frequency "
            "relations, QoS profiles, or RLC/PDCP profiles. `name` identifies the table; it "
            "contains one `item` element per row."
        ),
        "category": "File Format",
        "confidence": "high",
    },
    "item": {
        "description": (
            "One row of a `list` table, itself containing `p` elements for that row's "
            "columns (e.g. one `item` inside a neighbor-list `list` describes one neighbor "
            "cell's ARFCN, PCI, and other identifiers)."
        ),
        "category": "File Format",
        "confidence": "high",
    },
}

ATTRIBUTES: dict[str, dict] = {
    "distName": {
        "description": (
            "Distinguished Name: the full hierarchical path identifying exactly this object "
            "instance within the site, e.g. `MRBTS-1/LNBTS-1/LNCEL-1`. Each segment is "
            "`<ShortClassName>-<instanceId>`; reading the path tells you the object's full "
            "parentage without needing nested XML."
        ),
    },
    "class": {
        "description": (
            "The fully-qualified Managed Object Class name, formatted as "
            "`<namespace>:<ShortName>`. The namespace identifies the product-line data "
            "model (e.g. `com.nokia.srbts.*` / `com.nokia.mrbts.*` for AirScale, `NOKLTE:*` "
            "for Flexi Zone / older LTE); the short name after the colon is the actual "
            "object type (e.g. LNCEL, RMOD)."
        ),
    },
    "operation": {
        "description": (
            "What this file instructs the network element / management system to do with "
            "the object: \"create\" (add a new instance), \"update\" (change parameters on "
            "an existing instance), or \"delete\" (remove it)."
        ),
    },
    "version": {
        "description": (
            "The software/model build string the object's parameter set is defined against "
            "(e.g. `SBTS25R2_2502_100`, `TLF24R1_2317_10`). Different versions can add, "
            "remove, or redefine parameters for the same object class, so this pins which "
            "parameter dictionary revision applies."
        ),
    },
    "action": {
        "description": "What kind of audit event this log entry records (e.g. create, created, modified).",
    },
    "dateTime": {
        "description": "UTC timestamp of the logged event, in ISO-8601 format.",
    },
    "user": {
        "description": "The operator username or service account that performed the logged action.",
    },
    "appInfo": {
        "description": "The name of the tool that produced or modified this file, e.g. \"Nokia BTS Site Manager\" or \"Flexi TRS Manager\".",
    },
    "appVersion": {
        "description": "The version/build number of the tool named in appInfo.",
    },
    "type": {
        "description": "The kind of CM data set this is -- almost always \"plan\" (a configuration plan/snapshot to apply).",
    },
    "scope": {
        "description": "Whether this data set is a full data set (\"all\") or a partial delta.",
    },
    "id": {
        "description": "An internal numeric identifier for this data set, generated by the exporting tool.",
    },
    "name": {
        "description": "The parameter or table's identifier from Nokia's parameter dictionary.",
    },
}


def explain_element(tag: str) -> dict | None:
    return ELEMENTS.get(tag)


def explain_attribute(attr: str) -> dict | None:
    return ATTRIBUTES.get(attr)
